### ISSUE TITLE
skip already deleted tweets at the next run ?

### ISSUE THREAD

**Issue by dctt** [hugocaillard/tweets-cleaner#9]
Thanks for the code. it helped a lot.  
As for improvement;
At every run it tries to delete already deleted tweets as expected. I am not sure but If there can be a tracking of already deleted tweets and skip those at the next run, it would be great. If you have a lot to delete and run in different times it will help a lot.

**Comment by hugoclrd** [comment]
Hello dctt, thanks for your interest 🙂

Well if you re-download your archive, I guess it only gives you the tweet that are still online right? I'll look into a fresh archive

Otherwise we could probably create a file that would blacklist tweets ID to delete but I'm not sure it would be hyper useful.
I'll think about it but closing the issue for now

**Comment by dctt** [comment]
Thanks for the update.  Requesting new data and re-downloading is a solution but you can download only once in a month.  You have to wait days for it. It would be just better with blacklisting if someone has let's say 100k tweets to delete. Without a server it is quite a lot of time.  just saying.  thx for the good work again.
